### ISSUE TITLE
NoMethodError when trying to load home page 

### ISSUE THREAD

**Issue by albertalowe93** [sdutson12/skills_app#7]
@lisamchinn @sdutson12 just pulled from origin master and encountered this error when trying to load localhost:3000 / root. Do you guys know why? 

<img width="976" alt="Screen Shot 2019-07-16 at 16 06 15" src="https://user-images.githubusercontent.com/50481949/61322252-9faf6e80-a7e3-11e9-9b08-b50d6eb9144c.png">

**Comment by lisamchinn** [comment]
@albertalowe93 asking sebas
